# Generated by Django 3.2.5 on 2021-09-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='_json_file_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
