# Generated by Django 3.2.5 on 2021-09-22 14:54

from django.db import migrations, models
import nvd.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=nvd.uploader.get_file_upload_to)),
            ],
        ),
    ]
