# Generated by Django 3.2.5 on 2021-09-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0004_ctest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CTest',
        ),
    ]
